/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estructuras;

import java.awt.Color;
import estructuras.Logica.Log_in_Logica;
/**
 *
 * @author Caoba
 */
public class LOG_IN extends javax.swing.JFrame {

    /**
     * Creates new form LOG_IN
     */
    public LOG_IN() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        siguiente = new java.awt.Button();
        anterior = new java.awt.Button();
        Titulo = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        Contrasenia = new javax.swing.JLabel();
        Cuenta = new javax.swing.JTextField();
        Contra = new javax.swing.JPasswordField();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOG IN\n");
        setBackground(new java.awt.Color(0, 255, 204));
        setForeground(new java.awt.Color(51, 255, 153));
        getContentPane().setLayout(null);

        siguiente.setBackground(new java.awt.Color(255, 173, 148));
        siguiente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        siguiente.setLabel("Ingresar\n");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        getContentPane().add(siguiente);
        siguiente.setBounds(390, 410, 170, 70);

        anterior.setActionCommand("Anterior");
        anterior.setBackground(new java.awt.Color(255, 204, 51));
        anterior.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        anterior.setLabel("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });
        getContentPane().add(anterior);
        anterior.setBounds(70, 410, 170, 70);

        Titulo.setFont(new java.awt.Font("Cooper Black", 3, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 0));
        Titulo.setText("Login");
        getContentPane().add(Titulo);
        Titulo.setBounds(230, 10, 360, 140);

        Usuario.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("Password");
        getContentPane().add(Usuario);
        Usuario.setBounds(70, 230, 210, 60);

        Titulo1.setFont(new java.awt.Font("Cooper Black", 3, 48)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setText("Login");
        getContentPane().add(Titulo1);
        Titulo1.setBounds(230, 10, 360, 140);

        Contrasenia.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        Contrasenia.setForeground(new java.awt.Color(255, 255, 255));
        Contrasenia.setText("User");
        getContentPane().add(Contrasenia);
        Contrasenia.setBounds(70, 170, 170, 60);

        Cuenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(Cuenta);
        Cuenta.setBounds(269, 190, 170, 20);
        getContentPane().add(Contra);
        Contra.setBounds(270, 250, 170, 20);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estructuras/Imagenes/restaurant-high-resolution-wallpaper-for-desktop-background-download-images-free-colors-artworks-display-1920x1080.jpg"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 630, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_anteriorActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_siguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOG_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOG_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOG_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOG_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOG_IN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Contra;
    private javax.swing.JLabel Contrasenia;
    private javax.swing.JTextField Cuenta;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Usuario;
    private java.awt.Button anterior;
    private java.awt.Button siguiente;
    // End of variables declaration//GEN-END:variables
}
