/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estructuras;


import estructuras.Logica.Log_in_Logica;
import estructuras.Menu_Principal;
import estructuras.Menu_Principal;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
/**
 *
 * @author Caoba
 */
public class Log_In extends javax.swing.JFrame {

    /**
     * Creates new form LOG_IN
     */
    public Log_In() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        siguiente = new java.awt.Button();
        anterior = new java.awt.Button();
        Titulo = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        Contrasenia = new javax.swing.JLabel();
        cuenta = new javax.swing.JTextField();
        contra = new javax.swing.JPasswordField();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOG IN\n");
        setBackground(new java.awt.Color(0, 255, 204));
        setForeground(new java.awt.Color(51, 255, 153));
        getContentPane().setLayout(null);

        siguiente.setBackground(new java.awt.Color(255, 173, 148));
        siguiente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        siguiente.setLabel("Ingresar\n");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        getContentPane().add(siguiente);
        siguiente.setBounds(800, 520, 280, 90);

        anterior.setActionCommand("Anterior");
        anterior.setBackground(new java.awt.Color(255, 204, 51));
        anterior.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        anterior.setLabel("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });
        getContentPane().add(anterior);
        anterior.setBounds(180, 520, 280, 90);

        Titulo.setFont(new java.awt.Font("Cooper Black", 3, 80)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 0));
        Titulo.setText("Login");
        getContentPane().add(Titulo);
        Titulo.setBounds(460, 0, 360, 140);

        Usuario.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("Password");
        getContentPane().add(Usuario);
        Usuario.setBounds(340, 290, 250, 70);

        Contrasenia.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        Contrasenia.setForeground(new java.awt.Color(255, 255, 255));
        Contrasenia.setText("User");
        getContentPane().add(Contrasenia);
        Contrasenia.setBounds(340, 210, 170, 60);

        cuenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaActionPerformed(evt);
            }
        });
        getContentPane().add(cuenta);
        cuenta.setBounds(720, 210, 230, 50);

        contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraActionPerformed(evt);
            }
        });
        getContentPane().add(contra);
        contra.setBounds(720, 290, 230, 50);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estructuras/Imagenes/restaurant-high-resolution-wallpaper-for-desktop-background-download-images-free-colors-artworks-display-1920x1080.jpg"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 1700, 890);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        // TODO add your handling code here:
        Menu_Principal principal= new Menu_Principal();
                principal.setVisible(true);
            this.setVisible(false);
        
        
    }//GEN-LAST:event_anteriorActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        // TODO add your handling code here:
        Log_in_Logica logica=new Log_in_Logica();
       logica.LogIn();
       
        
        
    }//GEN-LAST:event_siguienteActionPerformed

    private void cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaActionPerformed
       
               
    }//GEN-LAST:event_cuentaActionPerformed

    private void contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_contraActionPerformed

    public JPasswordField getContra() {
        return contra;
    }

    public void setContra(JPasswordField contra) {
        this.contra = contra;
    }

    public JTextField getCuenta() {
        return cuenta;
    }

    public void setCuenta(JTextField cuenta) {
        this.cuenta = cuenta;
    }

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log_In().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contrasenia;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Usuario;
    private java.awt.Button anterior;
    private javax.swing.JPasswordField contra;
    private javax.swing.JTextField cuenta;
    private java.awt.Button siguiente;
    // End of variables declaration//GEN-END:variables
}
