/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estructuras;

import java.awt.Color;

/**
 *
 * @author Caoba
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientin = new java.awt.Button();
        personalin = new java.awt.Button();
        FondoMenuP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));
        getContentPane().setLayout(null);

        clientin.setActionCommand("CLIENTE");
        clientin.setBackground(new java.awt.Color(255, 204, 51));
        clientin.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        clientin.setLabel("CLIENTE ONLINE");
        clientin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientinActionPerformed(evt);
            }
        });
        getContentPane().add(clientin);
        clientin.setBounds(670, 230, 350, 130);

        personalin.setActionCommand("PERSONAL");
        personalin.setBackground(new java.awt.Color(255, 204, 51));
        personalin.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        personalin.setLabel("PERSONAL");
        personalin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalinActionPerformed(evt);
            }
        });
        getContentPane().add(personalin);
        personalin.setBounds(280, 230, 350, 130);

        FondoMenuP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estructuras/Imagenes/c2177ff23f862b515dd9f1517b011727-700.jpg"))); // NOI18N
        getContentPane().add(FondoMenuP);
        FondoMenuP.setBounds(60, -100, 1580, 1000);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientinActionPerformed
        // TODO add your handling code here:
       

    }//GEN-LAST:event_clientinActionPerformed

    private void personalinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalinActionPerformed
        // TODO add your handling code here:
         
             Log_In login= new Log_In();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_personalinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoMenuP;
    private java.awt.Button clientin;
    private java.awt.Button personalin;
    // End of variables declaration//GEN-END:variables
}
